// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data/collab_messages.proto

package edu.caltech.cs141b.hw5.android.data;

public final class CollabMessages {
  private CollabMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public enum StatusType
      implements com.google.protobuf.Internal.EnumLite {
    SUCCESS(0, 0),
    UNKNOWN_ERROR(1, 1),
    INVALID_REQUEST(2, 2),
    LOCK_UNAVAILABLE(3, 3),
    LOCK_EXPIRED(4, 4),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static StatusType valueOf(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 1: return UNKNOWN_ERROR;
        case 2: return INVALID_REQUEST;
        case 3: return LOCK_UNAVAILABLE;
        case 4: return LOCK_EXPIRED;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<StatusType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<StatusType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StatusType>() {
            public StatusType findValueByNumber(int number) {
              return StatusType.valueOf(number)
    ;        }
          };
    
    private final int index;
    private final int value;
    private StatusType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:cs141b.StatusType)
  }
  
  public enum RequestType
      implements com.google.protobuf.Internal.EnumLite {
    GET_DOCUMENT_LIST(0, 0),
    LOCK_DOCUMENT(1, 1),
    GET_DOCUMENT(2, 2),
    SAVE_DOCUMENT(3, 3),
    RELEASE_LOCK(4, 4),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static RequestType valueOf(int value) {
      switch (value) {
        case 0: return GET_DOCUMENT_LIST;
        case 1: return LOCK_DOCUMENT;
        case 2: return GET_DOCUMENT;
        case 3: return SAVE_DOCUMENT;
        case 4: return RELEASE_LOCK;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.valueOf(number)
    ;        }
          };
    
    private final int index;
    private final int value;
    private RequestType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:cs141b.RequestType)
  }
  
  public static final class DocumentMetaInfo extends
      com.google.protobuf.GeneratedMessageLite {
    // Use DocumentMetaInfo.newBuilder() to construct.
    private DocumentMetaInfo() {
      initFields();
    }
    private DocumentMetaInfo(boolean noInit) {}
    
    private static final DocumentMetaInfo defaultInstance;
    public static DocumentMetaInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public DocumentMetaInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private boolean hasKey;
    private java.lang.String key_ = "";
    public boolean hasKey() { return hasKey; }
    public java.lang.String getKey() { return key_; }
    
    // required string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private boolean hasTitle;
    private java.lang.String title_ = "";
    public boolean hasTitle() { return hasTitle; }
    public java.lang.String getTitle() { return title_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasKey) return false;
      if (!hasTitle) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasKey()) {
        output.writeString(1, getKey());
      }
      if (hasTitle()) {
        output.writeString(2, getTitle());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getKey());
      }
      if (hasTitle()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getTitle());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo, Builder> {
      private edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo result;
      
      // Construct using edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo();
        return builder;
      }
      
      protected edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo getDefaultInstanceForType() {
        return edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo other) {
        if (other == edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              setKey(input.readString());
              break;
            }
            case 18: {
              setTitle(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string key = 1;
      public boolean hasKey() {
        return result.hasKey();
      }
      public java.lang.String getKey() {
        return result.getKey();
      }
      public Builder setKey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = getDefaultInstance().getKey();
        return this;
      }
      
      // required string title = 2;
      public boolean hasTitle() {
        return result.hasTitle();
      }
      public java.lang.String getTitle() {
        return result.getTitle();
      }
      public Builder setTitle(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTitle = true;
        result.title_ = value;
        return this;
      }
      public Builder clearTitle() {
        result.hasTitle = false;
        result.title_ = getDefaultInstance().getTitle();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:cs141b.DocumentMetaInfo)
    }
    
    static {
      defaultInstance = new DocumentMetaInfo(true);
      edu.caltech.cs141b.hw5.android.data.CollabMessages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cs141b.DocumentMetaInfo)
  }
  
  public static final class LockedDocumentInfo extends
      com.google.protobuf.GeneratedMessageLite {
    // Use LockedDocumentInfo.newBuilder() to construct.
    private LockedDocumentInfo() {
      initFields();
    }
    private LockedDocumentInfo(boolean noInit) {}
    
    private static final LockedDocumentInfo defaultInstance;
    public static LockedDocumentInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public LockedDocumentInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // optional string lockedBy = 1;
    public static final int LOCKEDBY_FIELD_NUMBER = 1;
    private boolean hasLockedBy;
    private java.lang.String lockedBy_ = "";
    public boolean hasLockedBy() { return hasLockedBy; }
    public java.lang.String getLockedBy() { return lockedBy_; }
    
    // optional int64 lockedUntil = 2;
    public static final int LOCKEDUNTIL_FIELD_NUMBER = 2;
    private boolean hasLockedUntil;
    private long lockedUntil_ = 0L;
    public boolean hasLockedUntil() { return hasLockedUntil; }
    public long getLockedUntil() { return lockedUntil_; }
    
    // optional string key = 3;
    public static final int KEY_FIELD_NUMBER = 3;
    private boolean hasKey;
    private java.lang.String key_ = "";
    public boolean hasKey() { return hasKey; }
    public java.lang.String getKey() { return key_; }
    
    // required string title = 4;
    public static final int TITLE_FIELD_NUMBER = 4;
    private boolean hasTitle;
    private java.lang.String title_ = "";
    public boolean hasTitle() { return hasTitle; }
    public java.lang.String getTitle() { return title_; }
    
    // required string contents = 5;
    public static final int CONTENTS_FIELD_NUMBER = 5;
    private boolean hasContents;
    private java.lang.String contents_ = "";
    public boolean hasContents() { return hasContents; }
    public java.lang.String getContents() { return contents_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasTitle) return false;
      if (!hasContents) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasLockedBy()) {
        output.writeString(1, getLockedBy());
      }
      if (hasLockedUntil()) {
        output.writeInt64(2, getLockedUntil());
      }
      if (hasKey()) {
        output.writeString(3, getKey());
      }
      if (hasTitle()) {
        output.writeString(4, getTitle());
      }
      if (hasContents()) {
        output.writeString(5, getContents());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasLockedBy()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getLockedBy());
      }
      if (hasLockedUntil()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getLockedUntil());
      }
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getKey());
      }
      if (hasTitle()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getTitle());
      }
      if (hasContents()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getContents());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo, Builder> {
      private edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo result;
      
      // Construct using edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo();
        return builder;
      }
      
      protected edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo getDefaultInstanceForType() {
        return edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo other) {
        if (other == edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo.getDefaultInstance()) return this;
        if (other.hasLockedBy()) {
          setLockedBy(other.getLockedBy());
        }
        if (other.hasLockedUntil()) {
          setLockedUntil(other.getLockedUntil());
        }
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasContents()) {
          setContents(other.getContents());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              setLockedBy(input.readString());
              break;
            }
            case 16: {
              setLockedUntil(input.readInt64());
              break;
            }
            case 26: {
              setKey(input.readString());
              break;
            }
            case 34: {
              setTitle(input.readString());
              break;
            }
            case 42: {
              setContents(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string lockedBy = 1;
      public boolean hasLockedBy() {
        return result.hasLockedBy();
      }
      public java.lang.String getLockedBy() {
        return result.getLockedBy();
      }
      public Builder setLockedBy(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLockedBy = true;
        result.lockedBy_ = value;
        return this;
      }
      public Builder clearLockedBy() {
        result.hasLockedBy = false;
        result.lockedBy_ = getDefaultInstance().getLockedBy();
        return this;
      }
      
      // optional int64 lockedUntil = 2;
      public boolean hasLockedUntil() {
        return result.hasLockedUntil();
      }
      public long getLockedUntil() {
        return result.getLockedUntil();
      }
      public Builder setLockedUntil(long value) {
        result.hasLockedUntil = true;
        result.lockedUntil_ = value;
        return this;
      }
      public Builder clearLockedUntil() {
        result.hasLockedUntil = false;
        result.lockedUntil_ = 0L;
        return this;
      }
      
      // optional string key = 3;
      public boolean hasKey() {
        return result.hasKey();
      }
      public java.lang.String getKey() {
        return result.getKey();
      }
      public Builder setKey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = getDefaultInstance().getKey();
        return this;
      }
      
      // required string title = 4;
      public boolean hasTitle() {
        return result.hasTitle();
      }
      public java.lang.String getTitle() {
        return result.getTitle();
      }
      public Builder setTitle(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTitle = true;
        result.title_ = value;
        return this;
      }
      public Builder clearTitle() {
        result.hasTitle = false;
        result.title_ = getDefaultInstance().getTitle();
        return this;
      }
      
      // required string contents = 5;
      public boolean hasContents() {
        return result.hasContents();
      }
      public java.lang.String getContents() {
        return result.getContents();
      }
      public Builder setContents(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasContents = true;
        result.contents_ = value;
        return this;
      }
      public Builder clearContents() {
        result.hasContents = false;
        result.contents_ = getDefaultInstance().getContents();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:cs141b.LockedDocumentInfo)
    }
    
    static {
      defaultInstance = new LockedDocumentInfo(true);
      edu.caltech.cs141b.hw5.android.data.CollabMessages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cs141b.LockedDocumentInfo)
  }
  
  public static final class UnlockedDocumentInfo extends
      com.google.protobuf.GeneratedMessageLite {
    // Use UnlockedDocumentInfo.newBuilder() to construct.
    private UnlockedDocumentInfo() {
      initFields();
    }
    private UnlockedDocumentInfo(boolean noInit) {}
    
    private static final UnlockedDocumentInfo defaultInstance;
    public static UnlockedDocumentInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public UnlockedDocumentInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private boolean hasKey;
    private java.lang.String key_ = "";
    public boolean hasKey() { return hasKey; }
    public java.lang.String getKey() { return key_; }
    
    // required string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private boolean hasTitle;
    private java.lang.String title_ = "";
    public boolean hasTitle() { return hasTitle; }
    public java.lang.String getTitle() { return title_; }
    
    // required string contents = 3;
    public static final int CONTENTS_FIELD_NUMBER = 3;
    private boolean hasContents;
    private java.lang.String contents_ = "";
    public boolean hasContents() { return hasContents; }
    public java.lang.String getContents() { return contents_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasKey) return false;
      if (!hasTitle) return false;
      if (!hasContents) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasKey()) {
        output.writeString(1, getKey());
      }
      if (hasTitle()) {
        output.writeString(2, getTitle());
      }
      if (hasContents()) {
        output.writeString(3, getContents());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getKey());
      }
      if (hasTitle()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getTitle());
      }
      if (hasContents()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getContents());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo, Builder> {
      private edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo result;
      
      // Construct using edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo();
        return builder;
      }
      
      protected edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo getDefaultInstanceForType() {
        return edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo other) {
        if (other == edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasContents()) {
          setContents(other.getContents());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              setKey(input.readString());
              break;
            }
            case 18: {
              setTitle(input.readString());
              break;
            }
            case 26: {
              setContents(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string key = 1;
      public boolean hasKey() {
        return result.hasKey();
      }
      public java.lang.String getKey() {
        return result.getKey();
      }
      public Builder setKey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = getDefaultInstance().getKey();
        return this;
      }
      
      // required string title = 2;
      public boolean hasTitle() {
        return result.hasTitle();
      }
      public java.lang.String getTitle() {
        return result.getTitle();
      }
      public Builder setTitle(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTitle = true;
        result.title_ = value;
        return this;
      }
      public Builder clearTitle() {
        result.hasTitle = false;
        result.title_ = getDefaultInstance().getTitle();
        return this;
      }
      
      // required string contents = 3;
      public boolean hasContents() {
        return result.hasContents();
      }
      public java.lang.String getContents() {
        return result.getContents();
      }
      public Builder setContents(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasContents = true;
        result.contents_ = value;
        return this;
      }
      public Builder clearContents() {
        result.hasContents = false;
        result.contents_ = getDefaultInstance().getContents();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:cs141b.UnlockedDocumentInfo)
    }
    
    static {
      defaultInstance = new UnlockedDocumentInfo(true);
      edu.caltech.cs141b.hw5.android.data.CollabMessages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cs141b.UnlockedDocumentInfo)
  }
  
  public static final class RequestMessage extends
      com.google.protobuf.GeneratedMessageLite {
    // Use RequestMessage.newBuilder() to construct.
    private RequestMessage() {
      initFields();
    }
    private RequestMessage(boolean noInit) {}
    
    private static final RequestMessage defaultInstance;
    public static RequestMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public RequestMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // required .cs141b.RequestType requestType = 1;
    public static final int REQUESTTYPE_FIELD_NUMBER = 1;
    private boolean hasRequestType;
    private edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestType requestType_;
    public boolean hasRequestType() { return hasRequestType; }
    public edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestType getRequestType() { return requestType_; }
    
    // optional string documentKey = 2;
    public static final int DOCUMENTKEY_FIELD_NUMBER = 2;
    private boolean hasDocumentKey;
    private java.lang.String documentKey_ = "";
    public boolean hasDocumentKey() { return hasDocumentKey; }
    public java.lang.String getDocumentKey() { return documentKey_; }
    
    // optional .cs141b.LockedDocumentInfo lockedDoc = 3;
    public static final int LOCKEDDOC_FIELD_NUMBER = 3;
    private boolean hasLockedDoc;
    private edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo lockedDoc_;
    public boolean hasLockedDoc() { return hasLockedDoc; }
    public edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo getLockedDoc() { return lockedDoc_; }
    
    private void initFields() {
      requestType_ = edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestType.GET_DOCUMENT_LIST;
      lockedDoc_ = edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasRequestType) return false;
      if (hasLockedDoc()) {
        if (!getLockedDoc().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasRequestType()) {
        output.writeEnum(1, getRequestType().getNumber());
      }
      if (hasDocumentKey()) {
        output.writeString(2, getDocumentKey());
      }
      if (hasLockedDoc()) {
        output.writeMessage(3, getLockedDoc());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasRequestType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getRequestType().getNumber());
      }
      if (hasDocumentKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getDocumentKey());
      }
      if (hasLockedDoc()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLockedDoc());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage, Builder> {
      private edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage result;
      
      // Construct using edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage();
        return builder;
      }
      
      protected edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage getDefaultInstanceForType() {
        return edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage other) {
        if (other == edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestMessage.getDefaultInstance()) return this;
        if (other.hasRequestType()) {
          setRequestType(other.getRequestType());
        }
        if (other.hasDocumentKey()) {
          setDocumentKey(other.getDocumentKey());
        }
        if (other.hasLockedDoc()) {
          mergeLockedDoc(other.getLockedDoc());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestType value = edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestType.valueOf(rawValue);
              if (value != null) {
                setRequestType(value);
              }
              break;
            }
            case 18: {
              setDocumentKey(input.readString());
              break;
            }
            case 26: {
              edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo.Builder subBuilder = edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo.newBuilder();
              if (hasLockedDoc()) {
                subBuilder.mergeFrom(getLockedDoc());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLockedDoc(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required .cs141b.RequestType requestType = 1;
      public boolean hasRequestType() {
        return result.hasRequestType();
      }
      public edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestType getRequestType() {
        return result.getRequestType();
      }
      public Builder setRequestType(edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasRequestType = true;
        result.requestType_ = value;
        return this;
      }
      public Builder clearRequestType() {
        result.hasRequestType = false;
        result.requestType_ = edu.caltech.cs141b.hw5.android.data.CollabMessages.RequestType.GET_DOCUMENT_LIST;
        return this;
      }
      
      // optional string documentKey = 2;
      public boolean hasDocumentKey() {
        return result.hasDocumentKey();
      }
      public java.lang.String getDocumentKey() {
        return result.getDocumentKey();
      }
      public Builder setDocumentKey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDocumentKey = true;
        result.documentKey_ = value;
        return this;
      }
      public Builder clearDocumentKey() {
        result.hasDocumentKey = false;
        result.documentKey_ = getDefaultInstance().getDocumentKey();
        return this;
      }
      
      // optional .cs141b.LockedDocumentInfo lockedDoc = 3;
      public boolean hasLockedDoc() {
        return result.hasLockedDoc();
      }
      public edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo getLockedDoc() {
        return result.getLockedDoc();
      }
      public Builder setLockedDoc(edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLockedDoc = true;
        result.lockedDoc_ = value;
        return this;
      }
      public Builder setLockedDoc(edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo.Builder builderForValue) {
        result.hasLockedDoc = true;
        result.lockedDoc_ = builderForValue.build();
        return this;
      }
      public Builder mergeLockedDoc(edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo value) {
        if (result.hasLockedDoc() &&
            result.lockedDoc_ != edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo.getDefaultInstance()) {
          result.lockedDoc_ =
            edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo.newBuilder(result.lockedDoc_).mergeFrom(value).buildPartial();
        } else {
          result.lockedDoc_ = value;
        }
        result.hasLockedDoc = true;
        return this;
      }
      public Builder clearLockedDoc() {
        result.hasLockedDoc = false;
        result.lockedDoc_ = edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:cs141b.RequestMessage)
    }
    
    static {
      defaultInstance = new RequestMessage(true);
      edu.caltech.cs141b.hw5.android.data.CollabMessages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cs141b.RequestMessage)
  }
  
  public static final class ResponseMessage extends
      com.google.protobuf.GeneratedMessageLite {
    // Use ResponseMessage.newBuilder() to construct.
    private ResponseMessage() {
      initFields();
    }
    private ResponseMessage(boolean noInit) {}
    
    private static final ResponseMessage defaultInstance;
    public static ResponseMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ResponseMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // required .cs141b.StatusType statusType = 1;
    public static final int STATUSTYPE_FIELD_NUMBER = 1;
    private boolean hasStatusType;
    private edu.caltech.cs141b.hw5.android.data.CollabMessages.StatusType statusType_;
    public boolean hasStatusType() { return hasStatusType; }
    public edu.caltech.cs141b.hw5.android.data.CollabMessages.StatusType getStatusType() { return statusType_; }
    
    // optional string message = 2;
    public static final int MESSAGE_FIELD_NUMBER = 2;
    private boolean hasMessage;
    private java.lang.String message_ = "";
    public boolean hasMessage() { return hasMessage; }
    public java.lang.String getMessage() { return message_; }
    
    // repeated .cs141b.DocumentMetaInfo docMeta = 3;
    public static final int DOCMETA_FIELD_NUMBER = 3;
    private java.util.List<edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo> docMeta_ =
      java.util.Collections.emptyList();
    public java.util.List<edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo> getDocMetaList() {
      return docMeta_;
    }
    public int getDocMetaCount() { return docMeta_.size(); }
    public edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo getDocMeta(int index) {
      return docMeta_.get(index);
    }
    
    // optional .cs141b.LockedDocumentInfo lockedDoc = 4;
    public static final int LOCKEDDOC_FIELD_NUMBER = 4;
    private boolean hasLockedDoc;
    private edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo lockedDoc_;
    public boolean hasLockedDoc() { return hasLockedDoc; }
    public edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo getLockedDoc() { return lockedDoc_; }
    
    // optional .cs141b.UnlockedDocumentInfo unlockedDoc = 5;
    public static final int UNLOCKEDDOC_FIELD_NUMBER = 5;
    private boolean hasUnlockedDoc;
    private edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo unlockedDoc_;
    public boolean hasUnlockedDoc() { return hasUnlockedDoc; }
    public edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo getUnlockedDoc() { return unlockedDoc_; }
    
    private void initFields() {
      statusType_ = edu.caltech.cs141b.hw5.android.data.CollabMessages.StatusType.SUCCESS;
      lockedDoc_ = edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo.getDefaultInstance();
      unlockedDoc_ = edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasStatusType) return false;
      for (edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo element : getDocMetaList()) {
        if (!element.isInitialized()) return false;
      }
      if (hasLockedDoc()) {
        if (!getLockedDoc().isInitialized()) return false;
      }
      if (hasUnlockedDoc()) {
        if (!getUnlockedDoc().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasStatusType()) {
        output.writeEnum(1, getStatusType().getNumber());
      }
      if (hasMessage()) {
        output.writeString(2, getMessage());
      }
      for (edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo element : getDocMetaList()) {
        output.writeMessage(3, element);
      }
      if (hasLockedDoc()) {
        output.writeMessage(4, getLockedDoc());
      }
      if (hasUnlockedDoc()) {
        output.writeMessage(5, getUnlockedDoc());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasStatusType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getStatusType().getNumber());
      }
      if (hasMessage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getMessage());
      }
      for (edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo element : getDocMetaList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      if (hasLockedDoc()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getLockedDoc());
      }
      if (hasUnlockedDoc()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getUnlockedDoc());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage, Builder> {
      private edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage result;
      
      // Construct using edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage();
        return builder;
      }
      
      protected edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage getDefaultInstanceForType() {
        return edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.docMeta_ != java.util.Collections.EMPTY_LIST) {
          result.docMeta_ =
            java.util.Collections.unmodifiableList(result.docMeta_);
        }
        edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage other) {
        if (other == edu.caltech.cs141b.hw5.android.data.CollabMessages.ResponseMessage.getDefaultInstance()) return this;
        if (other.hasStatusType()) {
          setStatusType(other.getStatusType());
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        if (!other.docMeta_.isEmpty()) {
          if (result.docMeta_.isEmpty()) {
            result.docMeta_ = new java.util.ArrayList<edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo>();
          }
          result.docMeta_.addAll(other.docMeta_);
        }
        if (other.hasLockedDoc()) {
          mergeLockedDoc(other.getLockedDoc());
        }
        if (other.hasUnlockedDoc()) {
          mergeUnlockedDoc(other.getUnlockedDoc());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              edu.caltech.cs141b.hw5.android.data.CollabMessages.StatusType value = edu.caltech.cs141b.hw5.android.data.CollabMessages.StatusType.valueOf(rawValue);
              if (value != null) {
                setStatusType(value);
              }
              break;
            }
            case 18: {
              setMessage(input.readString());
              break;
            }
            case 26: {
              edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo.Builder subBuilder = edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addDocMeta(subBuilder.buildPartial());
              break;
            }
            case 34: {
              edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo.Builder subBuilder = edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo.newBuilder();
              if (hasLockedDoc()) {
                subBuilder.mergeFrom(getLockedDoc());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLockedDoc(subBuilder.buildPartial());
              break;
            }
            case 42: {
              edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo.Builder subBuilder = edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo.newBuilder();
              if (hasUnlockedDoc()) {
                subBuilder.mergeFrom(getUnlockedDoc());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setUnlockedDoc(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required .cs141b.StatusType statusType = 1;
      public boolean hasStatusType() {
        return result.hasStatusType();
      }
      public edu.caltech.cs141b.hw5.android.data.CollabMessages.StatusType getStatusType() {
        return result.getStatusType();
      }
      public Builder setStatusType(edu.caltech.cs141b.hw5.android.data.CollabMessages.StatusType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasStatusType = true;
        result.statusType_ = value;
        return this;
      }
      public Builder clearStatusType() {
        result.hasStatusType = false;
        result.statusType_ = edu.caltech.cs141b.hw5.android.data.CollabMessages.StatusType.SUCCESS;
        return this;
      }
      
      // optional string message = 2;
      public boolean hasMessage() {
        return result.hasMessage();
      }
      public java.lang.String getMessage() {
        return result.getMessage();
      }
      public Builder setMessage(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessage = true;
        result.message_ = value;
        return this;
      }
      public Builder clearMessage() {
        result.hasMessage = false;
        result.message_ = getDefaultInstance().getMessage();
        return this;
      }
      
      // repeated .cs141b.DocumentMetaInfo docMeta = 3;
      public java.util.List<edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo> getDocMetaList() {
        return java.util.Collections.unmodifiableList(result.docMeta_);
      }
      public int getDocMetaCount() {
        return result.getDocMetaCount();
      }
      public edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo getDocMeta(int index) {
        return result.getDocMeta(index);
      }
      public Builder setDocMeta(int index, edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.docMeta_.set(index, value);
        return this;
      }
      public Builder setDocMeta(int index, edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo.Builder builderForValue) {
        result.docMeta_.set(index, builderForValue.build());
        return this;
      }
      public Builder addDocMeta(edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.docMeta_.isEmpty()) {
          result.docMeta_ = new java.util.ArrayList<edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo>();
        }
        result.docMeta_.add(value);
        return this;
      }
      public Builder addDocMeta(edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo.Builder builderForValue) {
        if (result.docMeta_.isEmpty()) {
          result.docMeta_ = new java.util.ArrayList<edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo>();
        }
        result.docMeta_.add(builderForValue.build());
        return this;
      }
      public Builder addAllDocMeta(
          java.lang.Iterable<? extends edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo> values) {
        if (result.docMeta_.isEmpty()) {
          result.docMeta_ = new java.util.ArrayList<edu.caltech.cs141b.hw5.android.data.CollabMessages.DocumentMetaInfo>();
        }
        super.addAll(values, result.docMeta_);
        return this;
      }
      public Builder clearDocMeta() {
        result.docMeta_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional .cs141b.LockedDocumentInfo lockedDoc = 4;
      public boolean hasLockedDoc() {
        return result.hasLockedDoc();
      }
      public edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo getLockedDoc() {
        return result.getLockedDoc();
      }
      public Builder setLockedDoc(edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLockedDoc = true;
        result.lockedDoc_ = value;
        return this;
      }
      public Builder setLockedDoc(edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo.Builder builderForValue) {
        result.hasLockedDoc = true;
        result.lockedDoc_ = builderForValue.build();
        return this;
      }
      public Builder mergeLockedDoc(edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo value) {
        if (result.hasLockedDoc() &&
            result.lockedDoc_ != edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo.getDefaultInstance()) {
          result.lockedDoc_ =
            edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo.newBuilder(result.lockedDoc_).mergeFrom(value).buildPartial();
        } else {
          result.lockedDoc_ = value;
        }
        result.hasLockedDoc = true;
        return this;
      }
      public Builder clearLockedDoc() {
        result.hasLockedDoc = false;
        result.lockedDoc_ = edu.caltech.cs141b.hw5.android.data.CollabMessages.LockedDocumentInfo.getDefaultInstance();
        return this;
      }
      
      // optional .cs141b.UnlockedDocumentInfo unlockedDoc = 5;
      public boolean hasUnlockedDoc() {
        return result.hasUnlockedDoc();
      }
      public edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo getUnlockedDoc() {
        return result.getUnlockedDoc();
      }
      public Builder setUnlockedDoc(edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasUnlockedDoc = true;
        result.unlockedDoc_ = value;
        return this;
      }
      public Builder setUnlockedDoc(edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo.Builder builderForValue) {
        result.hasUnlockedDoc = true;
        result.unlockedDoc_ = builderForValue.build();
        return this;
      }
      public Builder mergeUnlockedDoc(edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo value) {
        if (result.hasUnlockedDoc() &&
            result.unlockedDoc_ != edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo.getDefaultInstance()) {
          result.unlockedDoc_ =
            edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo.newBuilder(result.unlockedDoc_).mergeFrom(value).buildPartial();
        } else {
          result.unlockedDoc_ = value;
        }
        result.hasUnlockedDoc = true;
        return this;
      }
      public Builder clearUnlockedDoc() {
        result.hasUnlockedDoc = false;
        result.unlockedDoc_ = edu.caltech.cs141b.hw5.android.data.CollabMessages.UnlockedDocumentInfo.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:cs141b.ResponseMessage)
    }
    
    static {
      defaultInstance = new ResponseMessage(true);
      edu.caltech.cs141b.hw5.android.data.CollabMessages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cs141b.ResponseMessage)
  }
  
  
  static {
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
